name: Compile and Deploy Firmware

on:
  push:
    branches: [ main, master ]
    # Richiesta 2: Il job parte SOLO se ci sono modifiche in questa cartella
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessario per fare il push delle modifiche

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sudo BINDIR=/usr/local/bin sh

      - name: Install ESP32 Platform and Libraries
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "LovyanGFX"
          arduino-cli lib install "Adafruit NeoPixel"

      - - name: Set Version Number
        run: |
          BASE_VERSION="1.2"
          
          # Calcolo: Numero attuale - Offset
          PATCH=$(( ${{ github.run_number }} ))
          
          VERSION="${BASE_VERSION}.${PATCH}"
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest.json
        # Aggiorna automaticamente la versione nel file manifest.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.NEW_VERSION }}\"/" manifest.json

      - name: Compile Firmware
        # Passiamo la versione anche al codice C++ come macro (opzionale ma utile)
        run: |
          mkdir -p ./bin
          arduino-cli compile --fqbn esp32:esp32:esp32s3 \
            --build-property "build.usb_mode=1" \
            --build-property "compiler.cpp.extra_flags=-DMOCHI_VERSION=\"${{ env.NEW_VERSION }}\"" \
            --output-dir ./bin \
            ./src/Mochi_mouse_v5/Mochi_mouse_v5.ino

      - name: Prepare Binary for Web
        # Rinominiamo il file per matchare quello che cerca il manifest
        run: mv bin/Mochi_mouse_v5.ino.merged.bin bin/firmware_merged.bin

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f bin/firmware_merged.bin  # <--- AGGIUNGI -f QUI
          git add manifest.json
          git commit -m "Automated build: ${{ env.NEW_VERSION }}" || echo "No changes to commit"
          git push